/* GENERATED by tools/build_questions.py — do not edit by hand. */
window.GAUNTLET_QUESTIONS = [
 {
  "id": "q01",
  "topic": "Vectors",
  "time": 60,
  "prompt": "<p>Compute (4, −3) + 2(−1, 5).</p>",
  "choices": [
   "(3, 2)",
   "(6, −13)",
   "(2, 7)",
   "(7, −1)"
  ],
  "answer": 2,
  "explain": "Scale first: 2(−1, 5) = (−2, 10). Then add: (4 − 2, −3 + 10) = (2, 7)."
 },
 {
  "id": "q02",
  "topic": "Vectors",
  "time": 60,
  "prompt": "<p>Find the length ‖(−7, 24)‖.</p>",
  "choices": [
   "17",
   "25",
   "31",
   "625"
  ],
  "answer": 1,
  "explain": "√(49 + 576) = √625 = 25. Squaring wipes out the minus sign."
 },
 {
  "id": "q03",
  "topic": "Vectors",
  "time": 60,
  "prompt": "<p>Find the length of the 3-D vector (2, 3, 6).</p>",
  "choices": [
   "11",
   "49",
   "√13",
   "7"
  ],
  "answer": 3,
  "explain": "√(4 + 9 + 36) = √49 = 7. All three components get squared."
 },
 {
  "id": "q04",
  "topic": "Vectors",
  "time": 60,
  "prompt": "<p>Mean-pool the word vectors (1, 5), (3, −1) and (5, 2) into one sentence vector.</p>",
  "choices": [
   "(9, 6)",
   "(3, 2)",
   "(4.5, 3)",
   "(3, <span class=\"fr\"><span>8</span><span>3</span></span>)"
  ],
  "answer": 1,
  "explain": "Add them: (9, 6). Divide by the 3 words: (3, 2)."
 },
 {
  "id": "q05",
  "topic": "Vectors",
  "time": 60,
  "prompt": "<p>Find the unit vector pointing the same way as (−8, 6).</p>",
  "choices": [
   "(0.8, 0.6)",
   "(−4, 3)",
   "(−<span class=\"fr\"><span>4</span><span>7</span></span>, <span class=\"fr\"><span>3</span><span>7</span></span>)",
   "(−0.8, 0.6)"
  ],
  "answer": 3,
  "explain": "The length is √(64 + 36) = 10. Divide each component by 10: (−0.8, 0.6)."
 },
 {
  "id": "q06",
  "topic": "Dot product & cosine",
  "time": 75,
  "prompt": "<p>Compute the dot product (3, −2) · (4, 5).</p>",
  "choices": [
   "2",
   "22",
   "(12, −10)",
   "9"
  ],
  "answer": 0,
  "explain": "(3)(4) + (−2)(5) = 12 − 10 = 2. A dot product is one number."
 },
 {
  "id": "q07",
  "topic": "Dot product & cosine",
  "time": 75,
  "prompt": "<p>Find the cosine similarity of (0, 5) and (3, 4).</p>",
  "choices": [
   "20",
   "0.8",
   "2",
   "1"
  ],
  "answer": 1,
  "explain": "Dot product 0 + 20 = 20. Both lengths are 5, so 20 ÷ (5 × 5) = 0.8."
 },
 {
  "id": "q08",
  "topic": "Dot product & cosine",
  "time": 75,
  "prompt": "<p>For what value of <em>k</em> is (<em>k</em>, −2) perpendicular to (5, 10)?</p>",
  "choices": [
   "−4",
   "20",
   "4",
   "<span class=\"fr\"><span>1</span><span>4</span></span>"
  ],
  "answer": 2,
  "explain": "Perpendicular means dot product 0: 5k − 20 = 0, so k = 4."
 },
 {
  "id": "q09",
  "topic": "Dot product & cosine",
  "time": 75,
  "prompt": "<p>Compute the 3-D dot product (1, −2, 4) · (3, 1, −1).</p>",
  "choices": [
   "5",
   "9",
   "(3, −2, −4)",
   "−3"
  ],
  "answer": 3,
  "explain": "(1)(3) + (−2)(1) + (4)(−1) = 3 − 2 − 4 = −3."
 },
 {
  "id": "q10",
  "topic": "Dot product & cosine",
  "time": 75,
  "prompt": "<p>Using only the <em>sign</em> of the dot product, which vector points broadly <strong>opposite</strong> to (2, 1)?</p>",
  "choices": [
   "(−3, −1)",
   "(1, −1)",
   "(−1, 2)",
   "(1, 3)"
  ],
  "answer": 0,
  "explain": "(2, 1) · (−3, −1) = −6 − 1 = −7. Negative means broadly opposite. The others give 1, 0 and 5."
 },
 {
  "id": "q11",
  "topic": "Chunking",
  "time": 120,
  "prompt": "<p>Give the chunk lengths.</p>",
  "choices": [
   "34 and 25",
   "34 and 26",
   "51 and 9",
   "17, 16, 16 and 9"
  ],
  "answer": 1,
  "explain": "17 + 16 + 1 = 34. Adding line 3 would make 51, over 40, so emit 34. Then 16 + 9 + 1 = 26.",
  "doc": {
   "text": "Charge the drone.\nCheck the props.\nFind open space.\nStay low.",
   "sep": "\n",
   "size": 40,
   "overlap": 0
  }
 },
 {
  "id": "q12",
  "topic": "Chunking",
  "time": 120,
  "prompt": "<p>Which line appears in <strong>both</strong> chunk 1 and chunk 2?</p>",
  "choices": [
   "“Read the guide.”",
   "“Tighten each bolt.”",
   "“Attach the legs.”",
   "None of them"
  ],
  "answer": 2,
  "explain": "Chunk 1 = 46. Pop while over 20: 46 → 32 → 16. “Read the guide.” goes too (32 is still over 20), so “Attach the legs.” carries.",
  "doc": {
   "text": "Open the box.\nRead the guide.\nAttach the legs.\nTighten each bolt.\nFlip the table over.",
   "sep": "\n",
   "size": 55,
   "overlap": 20
  }
 },
 {
  "id": "q13",
  "topic": "Chunking",
  "time": 120,
  "prompt": "<p>How many chunks come out?</p>",
  "choices": [
   "2",
   "4",
   "3",
   "1"
  ],
  "answer": 2,
  "explain": "The separator is 2 characters. 15 + 15 + 2 = 32. Then 23 + 16 + 2 = 41, over 40, so the last two stay apart: 32, 23, 16.",
  "doc": {
   "text": "Rain is likely.\n\nBring a jacket.\n\nThe game starts at six.\n\nParking is free.",
   "sep": "\n\n",
   "size": 40,
   "overlap": 0
  }
 },
 {
  "id": "q14",
  "topic": "Chunking",
  "time": 120,
  "prompt": "<p>What is chunk 1?</p>",
  "choices": [
   "“Stir.”, “Taste.” and “Add salt.” (22)",
   "“Stir.” by itself (5)",
   "“Stir.” through “Stir again.” (34)",
   "“Stir.” and “Taste.” (12)"
  ],
  "answer": 3,
  "explain": "5 + 6 + 1 = 12. Adding “Add salt.” makes 12 + 9 + 1 = 22, over 20. So chunk 1 is the first two lines.",
  "doc": {
   "text": "Stir.\nTaste.\nAdd salt.\nStir again.\nServe it hot.\nWash the pot.",
   "sep": "\n",
   "size": 20,
   "overlap": 0
  }
 },
 {
  "id": "q15",
  "topic": "Chunking edge cases",
  "time": 120,
  "prompt": "<p>How long is chunk 1?</p>",
  "choices": [
   "21",
   "31",
   "40",
   "32"
  ],
  "answer": 3,
  "explain": "9 + 11 + 1 = 21, then 21 + 10 + 1 = 32. That's equal to the size, not over it, so it fits.",
  "doc": {
   "text": "Aim high.\nTrain hard.\nRest well.\nRepeat.",
   "sep": "\n",
   "size": 32,
   "overlap": 0
  }
 },
 {
  "id": "q16",
  "topic": "Chunking edge cases",
  "time": 120,
  "prompt": "<p>What comes out of the splitter?</p>",
  "choices": [
   "4 chunks: the long line is cut into 25 + 25 + 7",
   "3 chunks, and the middle one is 57 characters",
   "2 chunks: the long line is thrown away",
   "1 chunk: everything glued together"
  ],
  "answer": 1,
  "explain": "Atoms are never cut and never thrown away. A too-long atom comes out whole, over the size.",
  "doc": {
   "text": "Hi.\nThis single line is far too long to fit inside one chunk.\nBye.",
   "sep": "\n",
   "size": 25,
   "overlap": 0
  }
 },
 {
  "id": "q17",
  "topic": "Chunking edge cases",
  "time": 120,
  "prompt": "<p>Give the chunk lengths.</p>",
  "choices": [
   "27, 29, 32",
   "27, 32",
   "27, 29, 17",
   "42, 32"
  ],
  "answer": 0,
  "explain": "Both times, popping stops at exactly 14 (not over 14), so one line carries. And the last chunk, 14 + 17 + 1 = 32, exactly fits.",
  "doc": {
   "text": "Grab a cart.\nFind the milk.\nGet some eggs.\nPay at the front.",
   "sep": "\n",
   "size": 32,
   "overlap": 14
  }
 },
 {
  "id": "q18",
  "topic": "Chunking edge cases",
  "time": 120,
  "prompt": "<p>How long is chunk 2?</p>",
  "choices": [
   "77",
   "86",
   "64",
   "85"
  ],
  "answer": 0,
  "explain": "Chunk 1 = 21, already under 25. But the long line must fit: 21 + 64 + 1 = 86, over 80. Pop “Sign in.” → 12 + 64 + 1 = 77.",
  "doc": {
   "text": "Sign in.\nPick a seat.\nThe lecture covers vectors, dot products, and cosine similarity.",
   "sep": "\n",
   "size": 80,
   "overlap": 25
  }
 },
 {
  "id": "q19",
  "topic": "Precision & recall in search",
  "time": 60,
  "prompt": "<p>A question has <strong>12 relevant</strong> sentences. You set <strong>k = 8</strong> and get <strong>6</strong> hits. Precision and recall?</p>",
  "choices": [
   "Precision 50%, recall 75%",
   "Precision 75%, recall 75%",
   "Precision 75%, recall 50%",
   "Precision 50%, recall 50%"
  ],
  "answer": 2,
  "explain": "Precision = hits ÷ k = 6 ÷ 8 = 75%. Recall = hits ÷ relevant = 6 ÷ 12 = 50%."
 },
 {
  "id": "q20",
  "topic": "Precision & recall in search",
  "time": 60,
  "prompt": "<p>A question has <strong>10 relevant</strong> sentences in a collection of 100. With <strong>k = 4</strong>, what is the <strong>best possible recall</strong>?</p>",
  "choices": [
   "40%",
   "100%",
   "4%",
   "25%"
  ],
  "answer": 0,
  "explain": "At most 4 hits come back, out of 10 relevant: 4 ÷ 10 = 40%."
 },
 {
  "id": "q21",
  "topic": "Precision & recall in search",
  "time": 60,
  "prompt": "<p>You raise k from 5 to 10. What can happen to <strong>recall</strong>?</p>",
  "choices": [
   "It goes up or stays the same",
   "It goes down",
   "It always doubles",
   "It could go either way"
  ],
  "answer": 0,
  "explain": "More results can only add hits, and the number of relevant sentences doesn't change. Recall can't fall."
 },
 {
  "id": "q22",
  "topic": "Precision & recall in search",
  "time": 60,
  "prompt": "<p>A collection of 50 sentences has <strong>5 relevant</strong> ones. With <strong>k = 10</strong>, the search finds all 5. Precision and recall?</p>",
  "choices": [
   "Precision 100%, recall 50%",
   "Precision 50%, recall 100%",
   "Precision 100%, recall 100%",
   "Precision 10%, recall 100%"
  ],
  "answer": 1,
  "explain": "Precision = 5 ÷ 10 = 50% (half the results are junk, unavoidably). Recall = 5 ÷ 5 = 100%."
 },
 {
  "id": "q23",
  "topic": "Confusion matrix",
  "time": 60,
  "prompt": "<p>A smart doorbell watches for delivered packages. A package arrives, but the doorbell reports “no package.” Which outcome is this?</p>",
  "choices": [
   "False positive",
   "False negative",
   "True positive",
   "True negative"
  ],
  "answer": 1,
  "explain": "The doorbell hunts for packages, so “package” is the positive. It said no, and it was wrong: a miss, a false negative."
 },
 {
  "id": "q24",
  "topic": "Confusion matrix",
  "time": 60,
  "prompt": "<p>An app screens <strong>80</strong> people for diabetes. <strong>16</strong> have it. The app flags <strong>20</strong>, and <strong>14</strong> of those really have it. Which matrix is right?</p>",
  "choices": [
   "TP 14, FP 6, FN 2, TN 58",
   "TP 14, FP 2, FN 6, TN 58",
   "TP 14, FP 6, FN 2, TN 60",
   "TP 16, FP 4, FN 0, TN 60"
  ],
  "answer": 0,
  "explain": "FP = 20 − 14 = 6. FN = 16 − 14 = 2. TN = 80 − 14 − 6 − 2 = 58."
 },
 {
  "id": "q25",
  "topic": "Confusion matrix",
  "time": 60,
  "prompt": "<p>What is the <strong>accuracy</strong>?</p><table class=\"qt cm\"><tr><td></td><th>Said yes</th><th>Said no</th></tr><tr><th>Really yes</th><td><b>40</b><small>TP</small></td><td><b>10</b><small>FN</small></td></tr><tr><th>Really no</th><td><b>10</b><small>FP</small></td><td><b>140</b><small>TN</small></td></tr></table>",
  "choices": [
   "90%",
   "70%",
   "10%",
   "80%"
  ],
  "answer": 0,
  "explain": "Correct calls ÷ everything: (40 + 140) ÷ 200 = 180 ÷ 200 = 90%."
 },
 {
  "id": "q26",
  "topic": "Confusion matrix",
  "time": 60,
  "prompt": "<p>An earthquake-warning AI is tested on <strong>1,000</strong> days, and <strong>2</strong> had an earthquake. It says “no earthquake” every single day. What is its accuracy?</p>",
  "choices": [
   "0.2%",
   "100%",
   "99.8%",
   "98%"
  ],
  "answer": 2,
  "explain": "It's right on 998 of 1,000 days: 99.8%. And it caught zero earthquakes. That's the accuracy trap."
 },
 {
  "id": "q27",
  "topic": "Confusion matrix",
  "time": 60,
  "prompt": "<p>A search-and-rescue drone looks for lost hikers. How many <strong>alerts</strong> did it raise?</p><table class=\"qt cm\"><tr><td></td><th>Drone said person</th><th>Drone said no one</th></tr><tr><th>Really a person</th><td><b>9</b><small>TP</small></td><td><b>3</b><small>FN</small></td></tr><tr><th>Really no one</th><td><b>6</b><small>FP</small></td><td><b>82</b><small>TN</small></td></tr></table>",
  "choices": [
   "12",
   "9",
   "15",
   "91"
  ],
  "answer": 2,
  "explain": "Alerts are the “said person” column: 9 + 6 = 15. The row, 9 + 3, counts the real people."
 },
 {
  "id": "q28",
  "topic": "Precision & recall",
  "time": 75,
  "prompt": "<p>A bird-song app listens for <strong>cardinals</strong>. Precision and recall?</p><table class=\"qt cm\"><tr><td></td><th>App said cardinal</th><th>App said no</th></tr><tr><th>Really cardinal</th><td><b>36</b><small>TP</small></td><td><b>4</b><small>FN</small></td></tr><tr><th>Really not</th><td><b>12</b><small>FP</small></td><td><b>148</b><small>TN</small></td></tr></table>",
  "choices": [
   "Precision 90%, recall 75%",
   "Precision 75%, recall 90%",
   "Precision 92%, recall 90%",
   "Precision 18%, recall 90%"
  ],
  "answer": 1,
  "explain": "Precision reads the column: 36 ÷ (36 + 12) = 75%. Recall reads the row: 36 ÷ (36 + 4) = 90%."
 },
 {
  "id": "q29",
  "topic": "Precision & recall",
  "time": 75,
  "prompt": "<p>A model flags <strong>25</strong> items with precision <strong>80%</strong> and recall <strong>50%</strong>. How many items were <strong>really positive</strong>?</p>",
  "choices": [
   "20",
   "25",
   "40",
   "45"
  ],
  "answer": 2,
  "explain": "80% of 25 flags are right: TP = 20. Those 20 are 50% of the real positives, so there are 40."
 },
 {
  "id": "q30",
  "topic": "Precision & recall",
  "time": 75,
  "prompt": "<p>An AI flags students for an <strong>academic-integrity hearing</strong>. Which should the school care about most?</p>",
  "choices": [
   "Recall: catch every single cheater",
   "Accuracy: it covers both mistakes",
   "Neither: they always rise together",
   "Precision: a false accusation does real harm"
  ],
  "answer": 3,
  "explain": "The harsh mistake here is the false alarm, an innocent student accused. That's precision."
 },
 {
  "id": "q31",
  "topic": "Precision & recall",
  "time": 75,
  "prompt": "<p>A model says <strong>yes to everything</strong>. What is its recall?</p>",
  "choices": [
   "0%",
   "50%",
   "It depends on the threshold",
   "100%"
  ],
  "answer": 3,
  "explain": "Every real positive gets a yes, so none are missed: recall = 100%. Its precision is terrible, though."
 }
];
